# SPDX-FileCopyrightText: 2026 dcel contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "dcel"
version = "0.6.11"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Implementation of doubly-connected edge list."
repository = "https://codeberg.org/topola/dcel"
documentation = "https://docs.rs/dcel"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["no_std"]
categories = ["data-structures", "no-std", "rust-patterns"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
stable-vec = ["dep:stable-vec", "maplike/stable-vec"]

[dependencies]
maplike = "0.7"
stable-vec = { version = "0.4", optional = true }
rstar = { version = "0.12", optional = true }
