// SPDX-FileCopyrightText: 2026 dcel contributors
//
// SPDX-License-Identifier: MIT OR Apache-2.0

// NOTE: The code here has been almost entirely generated by repeatedly and
// controllably prompting GPT-5.1 Codex and GPT-5.2 Codex over a few days. This
// is because this code is only used for debugging. The rest of `dcel`'s code
// was NOT generated this way, but was written manually and reviewed.

use macroquad::prelude::*;

use std::time::Duration;

use dcel::{EdgeId, FaceId, HalfEdgeId, StableDcel, VertexId};

fn world_to_screen(p: Vec2, scale: f32, source: Vec2, pan: Vec2) -> Vec2 {
    let p = p + pan;
    vec2(source.x + p.x * scale, source.y - p.y * scale)
}

fn screen_to_world(p: Vec2, scale: f32, source: Vec2, pan: Vec2) -> Vec2 {
    let world_x = (p.x - source.x) / scale - pan.x;
    let world_y = (source.y - p.y) / scale - pan.y;
    vec2(world_x, world_y)
}

fn draw_arrow(start: Vec2, end: Vec2, color: Color, thickness: f32) {
    let dir = end - start;
    let len = dir.length();
    if len < 1.0 {
        return;
    }

    let unit = dir / len;
    let head_len = 13.0_f32.min(len * 0.4);
    let head_width = 8.0_f32.min(len * 0.3);
    let tip = end;
    let base = end - unit * head_len;
    let normal = vec2(-unit.y, unit.x);
    let left = base + normal * (head_width * 0.5);
    let right = base - normal * (head_width * 0.5);

    draw_line(start.x, start.y, base.x, base.y, thickness, color);
    draw_triangle(tip, left, right, color);
}

fn to_world(x: i32, y: i32) -> Vec2 {
    vec2(x as f32, y as f32)
}

fn point_in_polygon(point: Vec2, polygon: &[Vec2]) -> bool {
    if polygon.len() < 3 {
        return false;
    }

    let mut inside = false;
    let mut j = polygon.len() - 1;
    for i in 0..polygon.len() {
        let pi = polygon[i];
        let pj = polygon[j];
        let intersects = ((pi.y > point.y) != (pj.y > point.y))
            && (point.x < (pj.x - pi.x) * (point.y - pi.y) / (pj.y - pi.y) + pi.x);
        if intersects {
            inside = !inside;
        }
        j = i;
    }

    inside
}

#[macroquad::main("DCEL Viewer")]
async fn main() {
    const HEX_MESH_3X3: [[[(i32, i32); 6]; 3]; 3] = [
        [
            [
                (87, -50),
                (0, -100),
                (-87, -50),
                (-87, 50),
                (0, 100),
                (87, 50),
            ],
            [
                (260, -50),
                (173, -100),
                (87, -50),
                (87, 50),
                (173, 100),
                (260, 50),
            ],
            [
                (433, -50),
                (346, -100),
                (260, -50),
                (260, 50),
                (346, 100),
                (433, 50),
            ],
        ],
        [
            [
                (173, 100),
                (87, 50),
                (0, 100),
                (0, 200),
                (87, 250),
                (173, 200),
            ],
            [
                (346, 100),
                (260, 50),
                (173, 100),
                (173, 200),
                (260, 250),
                (346, 200),
            ],
            [
                (520, 100),
                (433, 50),
                (346, 100),
                (346, 200),
                (433, 250),
                (520, 200),
            ],
        ],
        [
            [
                (87, 250),
                (0, 200),
                (-87, 250),
                (-87, 350),
                (0, 400),
                (87, 350),
            ],
            [
                (260, 250),
                (173, 200),
                (87, 250),
                (87, 350),
                (173, 400),
                (260, 350),
            ],
            [
                (433, 250),
                (346, 200),
                (260, 250),
                (260, 350),
                (346, 400),
                (433, 350),
            ],
        ],
    ];

    let cols = 3;
    let rows = 3;
    let mesh: Vec<Vec<(i32, i32)>> = HEX_MESH_3X3
        .iter()
        .flat_map(|row| row.iter())
        .map(|face| face.iter().copied().collect())
        .collect();
    let mut dcel: StableDcel<(i32, i32)> = StableDcel::new();
    dcel.insert_mesh(mesh);

    let (mesh_min, mesh_max, mesh_center) = {
        let mut min = vec2(f32::INFINITY, f32::INFINITY);
        let mut max = vec2(f32::NEG_INFINITY, f32::NEG_INFINITY);
        for vertex_idx in dcel.vertices().indices() {
            let vertex = VertexId::new(vertex_idx);
            let &(x, y) = dcel.vertex_weight(vertex);
            let p = to_world(x, y);
            min = vec2(min.x.min(p.x), min.y.min(p.y));
            max = vec2(max.x.max(p.x), max.y.max(p.y));
        }
        (min, max, (min + max) * 0.5)
    };

    let mut scale = 1.0_f32;
    let mut pan = Vec2::ZERO;
    let mut initialized = false;
    let mut last_drag_pos: Option<Vec2> = None;
    let mut selected_vertex: Option<VertexId> = None;
    let mut selected_face: Option<FaceId> = None;
    let mut rim_walk_face: Option<FaceId> = None;
    let mut rim_walk_edges: Vec<EdgeId> = Vec::new();
    let mut rim_walk_index: usize = 0;
    let mut rim_walk_reverse = false;
    let mut rim_walk_started = 0.0_f64;
    let mut rim_walk_last_step = 0.0_f64;
    let rim_walk_duration = 8.0_f64;
    let rim_walk_step = 0.12_f64;
    let rim_walk_delay = Duration::from_millis(40);

    loop {
        clear_background(BLACK);

        let screen_w = screen_width();
        let screen_h = screen_height();
        let padding = 40.0;
        let grid_w = (mesh_max.x - mesh_min.x).abs().max(1.0);
        let grid_h = (mesh_max.y - mesh_min.y).abs().max(1.0);
        let scale_x = (screen_w - 2.0 * padding) / grid_w;
        let scale_y = (screen_h - 2.0 * padding) / grid_h;
        let mut source = vec2(screen_w * 0.5, screen_h * 0.5);
        let fit_scale = scale_x.min(scale_y);
        let min_scale = fit_scale * 0.05;
        let max_scale = fit_scale * 50.0;
        if !initialized {
            scale = fit_scale * 0.9;
            pan = -mesh_center;
            initialized = true;
        }

        let (_, scroll_y) = mouse_wheel();
        if scroll_y.abs() > f32::EPSILON {
            let (mx, my) = mouse_position();
            let mouse = vec2(mx, my);
            let before = screen_to_world(mouse, scale, source, pan);
            let zoom = 1.1_f32.powf(scroll_y);
            scale = (scale * zoom).clamp(min_scale, max_scale);
            source = vec2(screen_w * 0.5, screen_h * 0.5);
            let after = screen_to_world(mouse, scale, source, pan);
            pan += after - before;
        }

        if is_mouse_button_down(MouseButton::Left) {
            let (mx, my) = mouse_position();
            let mouse = vec2(mx, my);
            if let Some(prev) = last_drag_pos {
                let delta = mouse - prev;
                pan += vec2(delta.x / scale, -delta.y / scale);
            }
            last_drag_pos = Some(mouse);
        } else {
            last_drag_pos = None;
        }

        if is_mouse_button_pressed(MouseButton::Left) {
            let (mx, my) = mouse_position();
            let mouse = vec2(mx, my);
            let mut nearest: Option<(VertexId, f32)> = None;
            let hit_radius = 10.0;

            for vertex_idx in dcel.vertices().indices() {
                let vertex = VertexId::new(vertex_idx);
                let &(x, y) = dcel.vertex_weight(vertex);
                let world = to_world(x, y);
                let screen = world_to_screen(world, scale, source, pan);
                let dist = screen.distance(mouse);
                if dist <= hit_radius {
                    if nearest.map_or(true, |(_, best)| dist < best) {
                        nearest = Some((vertex, dist));
                    }
                }
            }

            if let Some((vertex, _)) = nearest {
                match selected_vertex {
                    Some(selected) if selected == vertex => {
                        selected_vertex = None;
                    }
                    Some(selected) => {
                        dcel.insert_edge(selected, vertex);
                        selected_vertex = None;
                        rim_walk_face = None;
                        rim_walk_edges.clear();
                    }
                    None => {
                        selected_vertex = Some(vertex);
                    }
                }
            } else {
                selected_vertex = None;
                selected_face = None;
                let world_point = screen_to_world(mouse, scale, source, pan);
                let mut target_face: Option<FaceId> = None;

                for face_idx in dcel.faces().indices() {
                    let face = FaceId::new(face_idx);
                    if face == dcel.unbounded_face() || dcel.incident_half_edge(face).is_none() {
                        continue;
                    }

                    let face_vertices: Vec<Vec2> = dcel
                        .face_vertices(face)
                        .map(|vertex| {
                            let &(x, y) = dcel.vertex_weight(vertex);
                            to_world(x, y)
                        })
                        .collect();

                    if point_in_polygon(world_point, &face_vertices) {
                        target_face = Some(face);
                        break;
                    }
                }

                if let Some(face) = target_face {
                    let weight = (world_point.x.round() as i32, world_point.y.round() as i32);
                    dcel.triangulate_face_around_point(face, weight);
                    rim_walk_face = None;
                    rim_walk_edges.clear();
                }
            }
        }

        if is_mouse_button_pressed(MouseButton::Right) {
            let (mx, my) = mouse_position();
            let mouse = vec2(mx, my);
            let mut handled_rim_walk = false;
            if is_key_down(KeyCode::LeftShift) || is_key_down(KeyCode::RightShift) {
                let world_point = screen_to_world(mouse, scale, source, pan);
                let mut target_face: Option<FaceId> = None;

                for face_idx in dcel.faces().indices() {
                    let face = FaceId::new(face_idx);
                    if face == dcel.unbounded_face() || dcel.incident_half_edge(face).is_none() {
                        continue;
                    }

                    let face_vertices: Vec<Vec2> = dcel
                        .face_vertices(face)
                        .map(|vertex| {
                            let &(x, y) = dcel.vertex_weight(vertex);
                            to_world(x, y)
                        })
                        .collect();

                    if point_in_polygon(world_point, &face_vertices) {
                        target_face = Some(face);
                        break;
                    }
                }

                if let Some(face) = target_face {
                    if rim_walk_face == Some(face) {
                        rim_walk_reverse = !rim_walk_reverse;
                    } else {
                        rim_walk_reverse = false;
                    }
                    rim_walk_face = Some(face);
                    let max_edges = dcel.half_edges().indices().count();
                    rim_walk_edges = dcel.face_rim_edges(face).take(max_edges).collect();
                    rim_walk_index = if rim_walk_reverse && !rim_walk_edges.is_empty() {
                        rim_walk_edges.len() - 1
                    } else {
                        0
                    };
                    rim_walk_started = get_time();
                    rim_walk_last_step = rim_walk_started;
                    selected_face = Some(face);
                    selected_vertex = None;
                    handled_rim_walk = true;
                }
            }
            if !handled_rim_walk {
                let mut nearest: Option<(VertexId, f32)> = None;
                let hit_radius = 10.0;

                for vertex_idx in dcel.vertices().indices() {
                    let vertex = VertexId::new(vertex_idx);
                    let &(x, y) = dcel.vertex_weight(vertex);
                    let world = to_world(x, y);
                    let screen = world_to_screen(world, scale, source, pan);
                    let dist = screen.distance(mouse);
                    if dist <= hit_radius {
                        if nearest.map_or(true, |(_, best)| dist < best) {
                            nearest = Some((vertex, dist));
                        }
                    }
                }

                if let Some((vertex, _)) = nearest {
                    dcel.merge_faces_around_vertex(vertex);
                    selected_vertex = None;
                    selected_face = None;
                    rim_walk_face = None;
                    rim_walk_edges.clear();
                } else {
                    let world_point = screen_to_world(mouse, scale, source, pan);
                    let mut target_face: Option<FaceId> = None;

                    for face_idx in dcel.faces().indices() {
                        let face = FaceId::new(face_idx);
                        if face == dcel.unbounded_face() || dcel.incident_half_edge(face).is_none()
                        {
                            continue;
                        }

                        let face_vertices: Vec<Vec2> = dcel
                            .face_vertices(face)
                            .map(|vertex| {
                                let &(x, y) = dcel.vertex_weight(vertex);
                                to_world(x, y)
                            })
                            .collect();

                        if point_in_polygon(world_point, &face_vertices) {
                            target_face = Some(face);
                            break;
                        }
                    }

                    selected_face = match (selected_face, target_face) {
                        (Some(selected), Some(face)) if selected == face => None,
                        (_, face) => face,
                    };
                    selected_vertex = None;
                    rim_walk_face = None;
                    rim_walk_edges.clear();
                }
            }
        }

        if rim_walk_face.is_some() {
            let now = get_time();
            if now - rim_walk_started > rim_walk_duration {
                rim_walk_face = None;
                rim_walk_edges.clear();
                rim_walk_reverse = false;
            } else if rim_walk_edges.is_empty() {
                rim_walk_face = None;
                rim_walk_reverse = false;
            } else if now - rim_walk_last_step > rim_walk_step {
                if rim_walk_reverse {
                    if rim_walk_index == 0 {
                        rim_walk_face = None;
                        rim_walk_edges.clear();
                        rim_walk_reverse = false;
                    } else {
                        rim_walk_index -= 1;
                        rim_walk_last_step = now;
                    }
                } else {
                    if rim_walk_index + 1 >= rim_walk_edges.len() {
                        rim_walk_face = None;
                        rim_walk_edges.clear();
                    } else {
                        rim_walk_index += 1;
                        rim_walk_last_step = now;
                    }
                }
            }
        }

        let vertex_color = Color::new(0.35, 0.35, 0.35, 1.0);
        for vertex_idx in dcel.vertices().indices() {
            let vertex = VertexId::new(vertex_idx);
            let &(x, y) = dcel.vertex_weight(vertex);
            let world = to_world(x, y);
            let screen = world_to_screen(world, scale, source, pan);
            draw_circle(screen.x, screen.y, 4.0, vertex_color);
            let label = format!("{}", vertex.id());
            let font_size = 16.0;
            let dims = measure_text(&label, None, font_size as u16, 1.0);
            let label_pos = vec2(screen.x - dims.width * 0.5, screen.y - 6.0);
            draw_text(&label, label_pos.x, label_pos.y, font_size, WHITE);
        }

        if let Some(vertex) = selected_vertex {
            let highlight = Color::new(0.9, 0.2, 0.2, 1.0);
            for edge in dcel.vertex_rim_edges(vertex) {
                let (start_vertex, end_vertex) = dcel.edge_endpoints(edge);
                let &(sx, sy) = dcel.vertex_weight(start_vertex);
                let &(ex, ey) = dcel.vertex_weight(end_vertex);
                let start = world_to_screen(to_world(sx, sy), scale, source, pan);
                let end = world_to_screen(to_world(ex, ey), scale, source, pan);
                draw_line(start.x, start.y, end.x, end.y, 4.0, highlight);
            }
        }

        if let Some(face) = selected_face {
            let highlight = Color::new(0.2, 0.8, 0.3, 1.0);
            /*for edge in dcel.face_spokes(face) {
                let (start_vertex, end_vertex) = dcel.edge_endpoints(edge);
                let &(sx, sy) = dcel.vertex_weight(start_vertex);
                let &(ex, ey) = dcel.vertex_weight(end_vertex);
                let start = world_to_screen(to_world(sx, sy), scale, source, pan);
                let end = world_to_screen(to_world(ex, ey), scale, source, pan);
                draw_line(start.x, start.y, end.x, end.y, 4.0, highlight);
            }*/

            for interspoke in dcel.face_interspokes(face) {
                for edge in dcel.face_edges(interspoke) {
                    let (start_vertex, end_vertex) = dcel.edge_endpoints(edge);
                    let &(sx, sy) = dcel.vertex_weight(start_vertex);
                    let &(ex, ey) = dcel.vertex_weight(end_vertex);
                    let start = world_to_screen(to_world(sx, sy), scale, source, pan);
                    let end = world_to_screen(to_world(ex, ey), scale, source, pan);
                    draw_line(start.x, start.y, end.x, end.y, 4.0, highlight);
                }
            }
        }

        if rim_walk_face.is_some() && !rim_walk_edges.is_empty() {
            let edge = rim_walk_edges[rim_walk_index];
            let highlight = Color::new(1.0, 0.85, 0.2, 1.0);
            let (start_vertex, end_vertex) = dcel.edge_endpoints(edge);
            let &(sx, sy) = dcel.vertex_weight(start_vertex);
            let &(ex, ey) = dcel.vertex_weight(end_vertex);
            let start = world_to_screen(to_world(sx, sy), scale, source, pan);
            let end = world_to_screen(to_world(ex, ey), scale, source, pan);
            draw_line(start.x, start.y, end.x, end.y, 6.0, highlight);
        }

        for face_idx in dcel.faces().indices() {
            let face = FaceId::new(face_idx);
            if face == dcel.unbounded_face() || dcel.incident_half_edge(face).is_none() {
                continue;
            }

            let face_vertices: Vec<Vec2> = dcel
                .face_vertices(face)
                .map(|vertex| {
                    let &(x, y) = dcel.vertex_weight(vertex);
                    to_world(x, y)
                })
                .collect();

            if face_vertices.is_empty() {
                continue;
            }

            let center = face_vertices.iter().fold(Vec2::ZERO, |sum, p| sum + *p)
                / (face_vertices.len() as f32);
            let face_label = format!("{}", face.id());
            let face_font = 18.0;
            let face_dims = measure_text(&face_label, None, face_font as u16, 1.0);
            let face_screen = world_to_screen(center, scale, source, pan);
            let face_label_pos = vec2(
                face_screen.x - face_dims.width * 0.5,
                face_screen.y + face_dims.height * 0.5,
            );
            draw_text(
                &face_label,
                face_label_pos.x,
                face_label_pos.y,
                face_font,
                WHITE,
            );

            let draw_half_edge = |half_edge: HalfEdgeId, shift_sign: f32| {
                let source_id = dcel.source(half_edge);
                let dest_id = dcel.source(dcel.next_half_edge(half_edge));
                let &(ox, oy) = dcel.vertex_weight(source_id);
                let &(dx, dy) = dcel.vertex_weight(dest_id);
                let p0 = to_world(ox, oy);
                let p1 = to_world(dx, dy);

                let midpoint = (p0 + p1) * 0.5;
                let shift = (center - midpoint) * 0.2 * shift_sign;
                let shrink = 0.8;
                let start = midpoint + (p0 - midpoint) * shrink + shift;
                let end = midpoint + (p1 - midpoint) * shrink + shift;

                let start_screen = world_to_screen(start, scale, source, pan);
                let end_screen = world_to_screen(end, scale, source, pan);

                draw_arrow(
                    start_screen,
                    end_screen,
                    Color::new(0.1, 0.1, 0.4, 1.0),
                    2.0,
                );

                let label = format!("{}", half_edge.id());
                let font_size = 26.0;
                let text_dims = measure_text(&label, None, font_size as u16, 1.0);
                let center = (start_screen + end_screen) * 0.5;
                let label_pos = vec2(
                    center.x - text_dims.width * 0.5,
                    center.y + text_dims.height * 0.5,
                );
                let outline = Color::new(0.1, 0.1, 0.1, 1.0);
                let bold_offsets = [
                    vec2(-1.0, 0.0),
                    vec2(1.0, 0.0),
                    vec2(0.0, -1.0),
                    vec2(0.0, 1.0),
                ];
                for offset in bold_offsets {
                    draw_text(
                        &label,
                        label_pos.x + offset.x,
                        label_pos.y + offset.y,
                        font_size,
                        outline,
                    );
                }
                draw_text(&label, label_pos.x, label_pos.y, font_size, WHITE);

                let prev = dcel.prev_half_edge(half_edge);
                let next = dcel.next_half_edge(half_edge);
                let pn_label = format!("p{}, n{}", prev.id(), next.id());
                let pn_font = 16.0;
                let pn_dims = measure_text(&pn_label, None, pn_font as u16, 1.0);
                let pn_pos = vec2(
                    center.x - pn_dims.width * 0.5,
                    center.y + text_dims.height * 0.5 + pn_font,
                );
                draw_text(&pn_label, pn_pos.x, pn_pos.y, pn_font, WHITE);

                let cw = dcel.turn_half_edge(half_edge);
                let ccw = dcel.turn_back_half_edge(half_edge);
                let cw_label = format!("cw{}, ccw{}", cw.id(), ccw.id());
                let cw_font = 16.0;
                let cw_dims = measure_text(&cw_label, None, cw_font as u16, 1.0);
                let cw_pos = vec2(center.x - cw_dims.width * 0.5, pn_pos.y + cw_font);
                draw_text(&cw_label, cw_pos.x, cw_pos.y, cw_font, WHITE);

                let twin = dcel.twin(half_edge);
                let front_face = dcel.incident_face(half_edge);
                let twin_label = format!("t{} f{}", twin.id(), front_face.id());
                let twin_font = 16.0;
                let twin_dims = measure_text(&twin_label, None, twin_font as u16, 1.0);
                let twin_pos = vec2(center.x - twin_dims.width * 0.5, cw_pos.y + twin_font);
                draw_text(&twin_label, twin_pos.x, twin_pos.y, twin_font, WHITE);
            };

            for half_edge in dcel.face_half_edges(face) {
                draw_half_edge(half_edge, 1.0);
                if dcel.opposite_face(half_edge) == dcel.unbounded_face() {
                    draw_half_edge(dcel.twin(half_edge), -1.0);
                }
            }
        }

        if rim_walk_face.is_some() {
            std::thread::sleep(rim_walk_delay);
        }
        next_frame().await;
    }
}
